cmake_minimum_required(VERSION 4.1)
project(project_practic)

set(CMAKE_CXX_STANDARD 14)

add_executable(project_practic
        .idea/.gitignore
        .idea/editor.xml
        .idea/modules.xml
        .idea/project-practic.iml
        .idea/vcs.xml
        .idea/workspace.xml
        hello.cpp
        hello.exe
        main.cpp
        main.exe
        hello_err.cpp
        abc.cpp
        linear_equation.cpp
        square_equation.cpp
        array_stats.cpp
        sum_until_zero.cpp)
